In [ ]:
import numpy as np

##### Basics of Python

aatif

In [ ]:
!python --version

In [ ]:
23+56-34

In [ ]:
A=51
B=64
Sum= A+B
Sum

In [ ]:
A=51
B=64
Diff= A-B
Diff

In [ ]:
A=51
B=64
Product= A*B
Product

In [ ]:
a=5;
A=4;
a+A

In [ ]:
a= 3+5+45+4+56
a

In [ ]:
a = (2+4+55+34+4)
a

In [ ]:
a, b, c = 23, 54, "hi"
a,b,c

In [ ]:
a = b = c = "test"
b

In [1]:
a = "type"
type (a)

str

In [2]:
b = 5.2
type (b)

float

In [3]:
c = 3
type (c)

int

In [4]:
d = 2 +3j
type (d)

complex

In [5]:
a =2
b = 3.4 
sum = a+b
sub = a-b
print (sub,sum)

-1.4 5.4


#### List

In [16]:
sample_list = [10, 2.3, "ac", 2+3j]
sample_list

[10, 2.3, 'ac', (2+3j)]

In [13]:
type(sample_list)

list

In [3]:
sample_list[3]

(2+3j)

In [4]:
sample_list[3] = 65
sample_list

[10, 2.3, 'ac', 65]

In [5]:
sample_list[2] = "hello"
sample_list

[10, 2.3, 'hello', 65]

In [6]:
sample_list[1]= "hi"
sample_list

[10, 'hi', 'hello', 65]

In [7]:
sample_list.reverse()

In [8]:
sample_list

[65, 'hello', 'hi', 10]

In [9]:
sample_list[0]

65

In [10]:
sample_list[4]

IndexError: list index out of range

#### Tuple

In [22]:
sample_tuple = (2, 56 ,78, 6.4, "ad", 3+2j)
sample_tuple

(2, 56, 78, 6.4, 'ad', (3+2j))

In [23]:
sample_tuple[5]

(3+2j)

In [24]:
sample_tuple[0]

2

In [27]:
sample_tuple[3]

6.4

In [28]:
sample_tuple[3] = 1.8

TypeError: 'tuple' object does not support item assignment

#### Set

In [44]:
sample_set = {1,25,45,48,50,56,64,69,78,78,52,25,25,"ab", "aac"}
type(sample_set)

set

In [45]:
sample_set

{1, 25, 45, 48, 50, 52, 56, 64, 69, 78, 'aac', 'ab'}

In [46]:
sample_set[3]

TypeError: 'set' object is not subscriptable

In [47]:
sample_set.remove(50)
sample_set

{1, 25, 45, 48, 52, 56, 64, 69, 78, 'aac', 'ab'}

#### Dictionary

In [48]:
sample_dict = {"a":"alpha", 1:"first", 2:"second", 3:"third", 1:"fourth", 5:"fourth", 6:"sixth"}
type(sample_dict)

dict

In [49]:
sample_dict

{'a': 'alpha', 1: 'fourth', 2: 'second', 3: 'third', 5: 'fourth', 6: 'sixth'}

In [55]:
sample_dict["a"]

'alpha'

In [51]:
sample_dict

{'a': 'alpha', 1: 'fourth', 2: 'second', 3: 'third', 5: 'fourth', 6: 'sixth'}

In [52]:
sample_dict[2] = "ac"
sample_dict

{'a': 'alpha', 1: 'fourth', 2: 'ac', 3: 'third', 5: 'fourth', 6: 'sixth'}

#### String

In [101]:
a = "Hi how are you"

In [102]:
type(a)

str

In [103]:
a[4]

'o'

In [104]:
a[0]

'H'

In [105]:
a[2]

' '

In [106]:
a[10]

' '

In [107]:
a[3] = 'u'

TypeError: 'str' object does not support item assignment

#### Type conversion

In [110]:
a = 23.975
type(a)

float

#### NumPy

In [111]:
import numpy as np

In [113]:
simple_list = [6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [114]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [115]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
np.arange(7,92)

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
       58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
       75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91])

In [119]:
np.arange(5,35,6)

array([ 5, 11, 17, 23, 29])

In [121]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [137]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [135]:
np.linspace(0,20,9)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [128]:
np.linspace(0,10,8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [138]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [235]:
np.random.rand(2,4)

array([[0.48223008, 0.72719499, 0.74511416, 0.52255103],
       [0.29126313, 0.49133231, 0.73687305, 0.31088824]])

In [248]:
np.random.randn(2,4)

array([[ 0.86336541, -1.21522373, -0.21969755,  0.21920876],
       [-1.41710961,  0.08240173, -0.58218695,  1.44984666]])

In [249]:
np.random.rand(2,7)

array([[0.29069398, 0.47390811, 0.95621594, 0.48315754, 0.34473618,
        0.03944528, 0.79266912],
       [0.7650188 , 0.18315464, 0.69730481, 0.78467735, 0.24757806,
        0.98790682, 0.19931295]])

In [317]:
np.random.randint(2,5)

3

In [332]:
np.random.randint(20,56,100)

array([23, 52, 33, 49, 32, 31, 49, 35, 34, 41, 21, 31, 30, 43, 43, 35, 39,
       51, 49, 43, 29, 54, 33, 28, 37, 39, 50, 22, 49, 35, 47, 51, 46, 35,
       36, 24, 23, 37, 28, 36, 50, 30, 35, 25, 50, 40, 36, 23, 20, 35, 54,
       48, 45, 30, 37, 25, 33, 32, 29, 25, 31, 31, 33, 35, 27, 38, 24, 43,
       24, 49, 41, 44, 30, 38, 30, 47, 39, 26, 48, 54, 23, 24, 29, 52, 50,
       22, 48, 40, 37, 20, 45, 23, 44, 46, 44, 38, 24, 21, 42, 53])

In [214]:
sample_array=np.arange(20)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [343]:
rand_array=np.random.randint(0,10,5)
rand_array

array([5, 8, 4, 2, 8])

In [345]:
rand_array.min()

2

In [346]:
rand_array.argmin()

3

In [347]:
rand_array.max()

8

In [348]:
rand_array.argmax()

1

In [349]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [350]:
sample_array.dtype

dtype('int32')

In [352]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [353]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [356]:
a=np.random.rand(2,3)
a

array([[0.97780402, 0.46729807, 0.66452349],
       [0.6253821 , 0.74294444, 0.45321533]])

In [357]:
a.T

array([[0.97780402, 0.6253821 ],
       [0.46729807, 0.74294444],
       [0.66452349, 0.45321533]])

In [358]:
import numpy as np

In [374]:
sample_array=np.arange(10,22)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [375]:
sample_array=sample_array.reshape(6,2)
sample_array

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [376]:
sample_array[2:]

array([[14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [377]:
sample_array[1]=100
sample_array

array([[ 10,  11],
       [100, 100],
       [ 14,  15],
       [ 16,  17],
       [ 18,  19],
       [ 20,  21]])

In [404]:
sample_array=np.arange(10,21)
sample_array
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [405]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [406]:
subste_sample_array[:]=1001
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

#### Two-Dimensional array

In [407]:
sample_matrix=np.array(([24,13,2,15],[15,2,54,65],[56,76,24,7]))
sample_matrix

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [408]:
sample_matrix[0][2]

2

In [409]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [410]:
sample_matrix[1,1]

2

In [411]:
sample_matrix[1:3,2:4]

array([[54, 65],
       [24,  7]])

In [412]:
sample_matrix[1:,2:]

array([[54, 65],
       [24,  7]])

In [413]:
sample_matrix[2]

array([56, 76, 24,  7])

#### Custon Indexing

In [415]:
import numpy as np

In [418]:
sample_matrix=np.array(([30,10,1,23],[24,21,32,33],[6,76,24,7]))
sample_matrix

array([[30, 10,  1, 23],
       [24, 21, 32, 33],
       [ 6, 76, 24,  7]])

In [419]:
sample_matrix[:,1:]

array([[10,  1, 23],
       [21, 32, 33],
       [76, 24,  7]])

In [420]:
sample_matrix[1:,(2,3)]

array([[32, 33],
       [24,  7]])

In [422]:
sample_matrix[1:,2:]

array([[32, 33],
       [24,  7]])

In [423]:
sample_matrix[:,0,2:]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [424]:
sample_matrix[:,(0,2,3)]

array([[30,  1, 23],
       [24, 32, 33],
       [ 6, 24,  7]])

#### Selection Techniques

In [2]:
import numpy as np

In [4]:
sample_array=np.array([1,4,9,27,204])
sample_array

array([  1,   4,   9,  27, 204])

In [430]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [431]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12])

In [432]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481])

In [433]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583])

In [434]:
np.max(sample_array)

29

In [435]:
np.min(sample_array)

1

In [436]:
np.argmax(sample_array)

28

In [437]:
np.argmax(sample_array)

28

In [457]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841], dtype=int32)

In [5]:
np.std(sample_array)

78.02307351034052

In [442]:
np.mean(sample_array)

15.0

In [6]:
np.var(sample_array)

6087.6

In [446]:
sports=np.array(['golf', 'cricket', 'fball', 'cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

In [449]:
array=np.arange(5,13)
array

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [450]:
np.log(array)

array([1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665])

In [451]:
np.std(array)

2.29128784747792

In [452]:
np.exp(array)

array([1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05])

In [453]:
np.mean(array)

8.5

In [454]:
np.median(array)

8.5

In [456]:
np.square(array)

array([ 25,  36,  49,  64,  81, 100, 121, 144], dtype=int32)

In [464]:
random=np.random.rand(2,7)
random

array([[0.26078487, 0.88699957, 0.69565452, 0.34706494, 0.67597999,
        0.09264614, 0.50976234],
       [0.10290302, 0.94019579, 0.97784263, 0.23620092, 0.69845989,
        0.8201566 , 0.19596069]])

In [466]:
identity=np.eye(7,7)
identity

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [473]:
equal=np.linspace(0,30,10)
equal

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

In [475]:
natural= np.arange(1,21)
natural

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [476]:
np.sqrt(natural)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [479]:
np.round(np.sqrt(natural), decimals= 2)

array([1.  , 1.41, 1.73, 2.  , 2.24, 2.45, 2.65, 2.83, 3.  , 3.16, 3.32,
       3.46, 3.61, 3.74, 3.87, 4.  , 4.12, 4.24, 4.36, 4.47])

In [471]:
import pandas as pd